pub mod file_info;
pub mod analysis_response;
pub mod config;
pub mod cli;
pub mod analyze_repository_response;
pub mod files_cache;
pub mod analyze_request;
pub mod analyze_response;
pub mod api_response;
pub mod parse_error;
pub mod technology_stack;
pub mod stack_recommendation;
pub mod change_statistics;
pub mod apply_result;
pub mod validation_result;
pub mod category_stats;
mod change_statistics_builder;